### ISSUE TITLE
The returned id_token is not parseable

### ISSUE THREAD

**Issue by levalencia** [Azure-Samples/active-directory-angularjs-singlepageapp#17]
I have tried to use this code my own app but I have this error.

I have literally copied and pasted all the relevants part of the code.

Please see my question here
http://stackoverflow.com/questions/30925978/the-returned-id-token-is-not-parseable

**Comment by Neumeier** [comment]
I second that; I downloaded the sample application and it worked just fine but when attempting to apply it to something else (through careful, careful transferment) it throws this error when I run it on localhost, and gives me a 500 error when I publish and attempt to run it on Azure.

**Comment by talismax** [comment]
I had the same issue in IE until I noticed this:

![image](https://cloud.githubusercontent.com/assets/2261681/8890846/db4ee998-32d5-11e5-9c10-6a9308bec670.png)

Uncommenting that line made it work for me. I assume it always worked in Chrome. Works in both now.

**Comment by jmprieur** [comment]
I don't think that this reproes any longer with recent versions of ADAL.js. Feel free to reopen if it does.
