### ISSUE TITLE
SecurityTokenInvalidAudienceException when calling two different Web API's

### ISSUE THREAD

**Issue by marilag** [Azure-Samples/active-directory-angularjs-singlepageapp#21]
Hi. I'm getting this exception when I try to connect consecutively for the first time to 2 different Web API's from the SPA. I'm calling the services via a resolve in my routeconfig. It works when I refresh the page. 

Additional Information: Audience validation failed. Audiences: [Api2]. Did not match:  validationParameters.ValidAudience: [Api1] or validationParameters.ValidAudiences: 'null'

Hope you can tell me if I'm doing something wrong. Thanks

**Comment by MichelTaal** [comment]
Hi. Did you manage to solve your problem? I have the same probem. thanks

**Comment by jmprieur** [comment]
Did you try to add several endpoints with the endpoints property of ADAL.js config?
