### ISSUE TITLE
Suggestion for similar app

### ISSUE THREAD

**Issue by AmitJain06** [Azure-Samples/active-directory-angularjs-singlepageapp#23]
Hi , I need your help. Before i move further first i will tell about our project. Actually we are using Restful Web API at the backend. It is restful by the name only, for our benefits we are using Redis (cache) to manage session. This session is fully controlled by us and it is a key value pair mapped with user identity.

At the front end we are using Angular SPA. This app does not contains any web api, or any api controller. When this app starts we intialized some Side Bar and Header Bar on to the the view. This side bar and header bar contains some options to navigate through the application. To generate this side bar and header bar secured Web api is used (disscussed above).

Only after generating side bar and header nav that routing will takes place for consecutive navigation and requests. All other consecutive requests are dependent on some data that is set at the time of side bar and header bar is generated. (We are actully following John Papa clean coding pattern.)

Our API is secured with Azure Active Directory Identity Provider.
And we are using ADAL to secure our front end routes.

Now we come to the problem: approx in one hour ADAL trying to renew the token, that is successful. But when it redirect to our app, the app will reinitialized and all the side bar , header bar are goes out and app come to the initial state. Because current request is depending upon previously stored data so current request is also not fullfilled.

Please suggest me some solution.

**Comment by jmprieur** [comment]
We've created another sample, written in plain JavaScript, and using ADAL.js 1.0.15, which supports user interactions in case additional claims are needed:  
See https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof, in the branch named additionalClaimsSupport
