### ISSUE TITLE
Try to clone git repo - asks for username and password - fails and does not download

### ISSUE THREAD

**Issue by nigel-dewar** [Azure-Samples/active-directory-angularjs-singlepageapp#25]
Why do you have this so you must provide username and password to clone it?

**Comment by rglos** [comment]
The documentation is incorrect.  It's not

`https://github.com/Azure-Samples/SinglePageApp-DotNet.git`

but

`https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp.git`

**Comment by danieldobalian** [comment]
Docs have been updated: #30
