### ISSUE TITLE
The 'Tenant' option must be provided

### ISSUE THREAD

**Issue by boydcster** [Azure-Samples/active-directory-angularjs-singlepageapp#27]
This example is exactly what I need for a project, but I've been unable to get it working. The error message is the 'Tenant' option must be provided. I've provided the Tenant option in the StartupAuth as shown below:

app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Audience = ConfigurationManager.AppSettings["<client id>"],
                    Tenant = ConfigurationManager.AppSettings["<tenant name>"]
                });

Tenant name is my Azure AD tenant name and client id is my id as registered with the app. Any hints about why this might not be working? Any help appreciated.

**Comment by AmazingJaze** [comment]
@boydcster did you ever figure this out? I am running into the same problem myself.

**Comment by Dismissile** [comment]
Did you actually leave them blank like that? 

You should be using the ida:Audience and ida:Tenant values:

app.UseWindowsAzureActiveDirectoryBearerAuthentication(
new WindowsAzureActiveDirectoryBearerAuthenticationOptions
{
Audience = ConfigurationManager.AppSettings["ida:Audience"],
Tenant = ConfigurationManager.AppSettings["ida:Tenant"]
});

These should be defined in your web.config:

<appSettings>
    <add key="ida:Tenant" value="Enter your tenant name here e.g. contoso.onmicrosoft.com" />
    <add key="ida:Audience" value="Enter your clientId here e.g. e9a5a8b6-8af7-4719-9821-0deef255f68e" />
  </appSettings>

tenant is your Azure AD tenant and will be the same for all applications using your Azure AD
clientId is different for each application you create in Azure AD

**Comment by jmprieur** [comment]
You can also use the configuration scripts provided with the sample.
