### ISSUE TITLE
Step 1 of the README.md give wrong repo url

### ISSUE THREAD

**Issue by AmazingJaze** [Azure-Samples/active-directory-angularjs-singlepageapp#30]
Instead of: 
`git clone https://github.com/Azure-Samples/SinglePageApp-DotNet.git`
Shouldn't it be:
`git clone https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp.git`
?

**Comment by dhodgin** [comment]
Yes i noticed this too. will submit a PR for it

**Comment by danieldobalian** [comment]
Fixed here: #35
