### ISSUE TITLE
ADFS 2016 On Premise

### ISSUE THREAD

**Issue by robv8r** [Azure-Samples/active-directory-angularjs-singlepageapp#33]
How can I adapt this example to use ADFS 2016 On Premise?

**Comment by jmprieur** [comment]
I believe that just updating the instance and tenant in the app.js file would do:
https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp/blob/master/TodoSPA/App/Scripts/app.js#L19

config = {         
         instance: 'https://fs.domain./',
         tenant: 'adfs',
 ...
}
