### ISSUE TITLE
Refresh Token not working 

### ISSUE THREAD

**Issue by nikhil263** [Azure-Samples/active-directory-angularjs-singlepageapp#36]
I am using adal.js with angular. Everything work as expected except the token refreshing.
Indeed, if after 1 hour I do anything that issues an XHR to a protected resource then no more token is sent along with the request and I get stuck with a 401.
Shouldn’t be the token renewed silently by the hidden iframe?

**Comment by jmprieur** [comment]
If user interaction was needed for the renewal (for instance with conditional access this was not happening so far). https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp/pull/43 brings a better experience enabling user interaction.
