### ISSUE TITLE
Using Ws-federation Identity provider in the place of sts - url

### ISSUE THREAD

**Issue by swathi04c** [Azure-Samples/active-directory-angularjs-singlepageapp#37]
Hi I wanted to know if I can configure WS-Federation metadata xml obtained from azure ACS in this sample as below
adalProvider.init(
        {
           instance: 'https://sample.accesscontrol.windows.net/FederationMetadata/2007-        06/FederationMetadata.xml',
             tenant: 'adfs',                      // this should be adfs
              clientId: 'https://localhost:44359/'
        }
If yes do I need to add additional settings?

**Comment by jmprieur** [comment]
@swathi04c : did you find the answer to your question (I know it's very old)
Closing the issue for now.
