### ISSUE TITLE
Error description:AADSTS65001: The user or administrator has not consented to use the application with ID '4d47e75e-a79e-46ee-97d4-a540ca28f2fb'. Send an interactive authorization request for this user and resource.

### ISSUE THREAD

**Issue by zmyvszk** [Azure-Samples/active-directory-angularjs-singlepageapp#42]
I have an onbehalfof web api working very well, trying to call that API from my angular client, did every configuration, and added permission to the Web API also. The angular client can also get access to MS Graph, but not able to call my local host onbehalfof API. If anyone can help that would be appreciate!

**Comment by pradeemi** [comment]
Same with me

**Comment by jmprieur** [comment]
Thanks for your feedback @zmyvszk and @pradeemi 

In ADAL JS 1.0.15, we've just added 2 new APIS, acquireTokenRedirect and acquireTokenPopup allowing you to acquire token interactively with the help of a UI. In previous versions of Adal.js, we only supported acquireToken api which used a hidden iframe to acquire a token for a resource. But the AcquireToken API would fail silently if the cookies are not sent with the request or the session is expired with AAD or acquiring the token required additional interaction (like in the case you mention). 
You can now call acquireTokenRedirect/acquireTokenPopup on this failure which would show a UI where users can enter their credentials, or provide more consent, and renew their session with AAD to get an access token.

https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp/pulls updates the sample with ADAL.Js 1.0.15. 
closing this issue. Feel free to re-open if this still reproes for you

**Comment by RehanSaeed** [comment]
@jmprieur I get the same problem but my users are already logged in and I have hit the 'Grant Permissions' button in the Azure portal. Here is what I'm seeing:

1. User visits site for first time.
2. Redirect to Azure to login.
3. Azure redirects back to site, user is now logged in.
4. Site makes a GET request using `aquireToken`. This works for Azure admin users but all others were erroring (AADSTS65001) complaining about a consent screen, so I call `acquireTokenRedirect` but now the user is redirected back to a login screen and additional consent screen.
5. Redirect back to site and site can now perform GET requests.

Is there a way I can perform a single login and have all the permissions I need to perform GET requests?

**Comment by jmprieur** [comment]
what probably happens is while accessing the resource, this resource discovers that the user needs to provide more consent, or needs to do conditional access, and therefore it sends a interaction_required error. 
- the conditional access interaction is explained in this documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-conditional-access-developer
- also illustrated by this sample:
https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca

**Comment by GordonLam** [comment]
There is a case when your Web App and Web Api App are in different AAD tenant, then you must re-consent.
That's a special/headache case for multi-tenant app...
