### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by mleziva** [Azure-Samples/active-directory-angularjs-singlepageapp#45]
Used the powershell script to register the application in Azure AD. That worked, but when I run the application and try to login, my login does not succeed and it continuously redirects me back to the login page without an error message.

**Comment by jmprieur** [comment]
@mleziva can you please tell us a bit more. Which browser do you use (did you try with Chrome). are you using work/school accounts or Microsoft Personal Accounts (MSA)

**Comment by wxb1** [comment]
I experienced a similar problem. I used a AZURE AD user id/password. I used IE11. I used VS EXPRESS 2017. I could not get it work with this configuration. I could login but the website never reflected that I logged in. I would love some help getting this to work in IE11. I spent a good 30-45 minutes stepping through the code and trying to research the issue. Then I tried Edge and it works perfectly in Edge. But I don't believe the debugger breakpoints work in Edge.  I don't have any more time to work on this today. Can you help point me in the right direction to get this to work for IE11? From what I can tell the token being returned is invalid. The status response back from adal is "Invalid_State" in IE11...

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
