### ISSUE TITLE
EXAMPLES WITHOUT VISUAL STUDIO

### ISSUE THREAD

**Issue by M0rdr3d** [Azure-Samples/active-directory-angularjs-singlepageapp#48]
PLEASE THE COMMUNITY NEEDS EXAMPLE WITHOUT VISUAL STUDIO AT ALL, WITHOUT WINDOWS....

**Comment by jmprieur** [comment]
Thanks for the feedback, @M0rdr3d. 
How would you prefer the Web app to be served? with node.js? or Python? or another solution? how would you do?

**Comment by M0rdr3d** [comment]
@jmprieur Node.js is perfect but anything that runs on gnu/linux or mac directly is Oki doki. Thanks for the response !!!

**Comment by efredz** [comment]
I'm having the same problem. This sample app can't be run in linux or macosx (which is what most of the web developers are going to use).

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
