### ISSUE TITLE
Why should I mention in the body the controller that call adal.login() 

### ISSUE THREAD

**Issue by faissaal7** [Azure-Samples/active-directory-angularjs-singlepageapp#51]
if i didn't mention  the ng-controller in the body for html login fails

this is my config:
fo

```
.when('/login', {
                        templateUrl: 'login.tpl.html',
                        controller: 'LoginCtrl'
                    })
```
login.tpl.html contains a button with an action in the controller loginWithAdal

```
$scope.loginWithAdal = function(){
             adal.login
}
```

ADAL will work fine if i put controller in the body : `<body ng-controller="LoginCtrl">`

But when I use `<body>` adal will not work and return a message saying that _The returned id_token is not parseable._

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
