### ISSUE TITLE
I was wondering if it is possible to add domain_hint or login_hint for the OAuth2 authorize? 

### ISSUE THREAD

**Issue by tmfahim** [Azure-Samples/active-directory-angularjs-singlepageapp#52]
I am developing a SPA that use AAD for authentication and then call an Web API. I was wondering if it is possible to add domain_hint or login_hint for the OAuth2 authorize action to avoid Home Realm prompt? If yes, where do in the code I should include this? Thanks for your help.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
