### ISSUE TITLE
When I clicked "login" on the top right corner, nothing happened.

### ISSUE THREAD

**Issue by ShirleyCAT2016** [Azure-Samples/active-directory-angularjs-singlepageapp#53]
Hi,

I can only view the index page. When I clicked on "login", or "Todo List" tab, nothing happened. Can anyone give hints?

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
