### ISSUE TITLE
Suggestion for new sample app

### ISSUE THREAD

**Issue by dgodwin1175** [Azure-Samples/active-directory-angularjs-singlepageapp#54]
Hi,

I am struggling to get the following architecture up and running and would love to see a sample that describes how to do it.
- Angular SPA front end, communicates to a (self-hosted) webapi (both SPA and WebApi share the same native app id)
- User login is controlled by adal.js on angular front end.
- WebApi receives the bearer token from the SPA api calls
- WebApi uses the on-behalf of flow to get a new token to call a downstream API

Would love to know if this scenario is feasible, and worth pursuing as a sample app.
Thanks.

**Comment by Kirtlander** [comment]
+1
Would love to see this in the now not-so-new Angular 2+ (now officially V5) - [http://Angular.io](url)

**Comment by bcrosser** [comment]
+1
This sample doesn't really work, it's too confusing.  Please create some new sample SPA auth apps.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
