### ISSUE TITLE
Issue with the bearer token

### ISSUE THREAD

**Issue by SalimDr** [Azure-Samples/active-directory-angularjs-singlepageapp#55]
Hello i have implemented the ADFS 2016 and the sample.
The login works and the userdata page works (get all user info) but when i tried to go to the todo page it display a 401 for the get query /api/TodoList.
Can anyone help me please.
Thanks,

**Comment by jrmcdona** [comment]
Did you figure this out?

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
