### ISSUE TITLE
Issue Signing in - when pressed ToDo tab

### ISSUE THREAD

**Issue by rakshithca** [Azure-Samples/active-directory-angularjs-singlepageapp#59]
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '09a0fb5b-46ff-4fe1-9d69-65f4719daccc'.

**Comment by TiagoBrenck** [comment]
This sample has been archived.

The newer one can be found at: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2
