### ISSUE TITLE
Authentication works ok but then the WebAPI authentication fails.

### ISSUE THREAD

**Issue by johnkattenhorn** [Azure-Samples/active-directory-angularjs-singlepageapp#8]
I've configured this sample as per the documentation and I can login no problem and use the User menu option to see the users details etc.

However when I click on the Todo List I get a message {"Message":"Authorization has been denied for this request."} and is returning a 401 in the browser; Setting a break point side the TodoListController confirms there no principal available.

 I do see the following in the console window in the browser as well :+1: 

The returned id_token is not parseable. adal.js:959

I've check that the  tenant and the clientid are the same in both the web.config and the app.js.

**Comment by jefftindall** [comment]
I was fighting with a similar issue recently and was able to get both the SPA and the WebApi to work in the same project.  The solution was to initialize the authentication twice (once for each method).  You can do this by setting the AuthenticationType property on the AuthenticationOptions.

    public void ConfigureAuth(IAppBuilder app)
    {
        app.UseWindowsAzureActiveDirectoryBearerAuthentication(
            new WindowsAzureActiveDirectoryBearerAuthenticationOptions
            {
                Audience = ConfigurationManager.AppSettings["ida:ClientID"],
                Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                // Support for SPA tokens
                AuthenticationType = "SPA"
            });
        app.UseWindowsAzureActiveDirectoryBearerAuthentication(
            new WindowsAzureActiveDirectoryBearerAuthenticationOptions
            {
                Audience = ConfigurationManager.AppSettings["ida:Audience"],
                Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                // Support for WebApi tokens
                AuthenticationType = "WebApi"
            });
    }

**Comment by jcbowyer** [comment]
I am having the same issue and I am not clear of the solution from these recommendations.  
1.  Is there a fork that fixes the issue, is so where?
2.  I set my audience and clientid both to my client id and i still get the issue 
3.  I did the double call and i still get the issue.

Thanks for the help

**Comment by mohanskumar** [comment]
I do have the same issue with adal 1.0.13. Getting the token successfully, however getting 401 when calling API's using the same token.
